from __future__ import annotations

PROTECTED_USERS = {"SYS", "SYSTEM"}
PROTECTED_PROGRAM_TOKENS = {"pmon", "smon", "dbw", "lgwr", "ckpt"}
PROTECTED_MAINTENANCE_TOKENS = {
    "rman",
    "dbms_scheduler",
    "jobq",
    "cjq",
    "dbms_stats",
    "datapump",
    "expdp",
    "impdp",
}
PROTECTED_TABLESPACES = {"SYSTEM", "SYSAUX"}

ALLOWED_ACTIONS = {"kill_session", "clear_blocking_lock", "extend_tablespace"}

SAFE_SQL_PREFIXES = {
    "clear_blocking_lock": ("ALTER SYSTEM KILL SESSION", "ALTER SYSTEM DISCONNECT SESSION"),
    "kill_session": ("ALTER SYSTEM KILL SESSION", "ALTER SYSTEM DISCONNECT SESSION"),
    "extend_tablespace": ("ALTER TABLESPACE ", "ALTER DATABASE DATAFILE "),
}

BLOCKED_SQL_KEYWORDS = {"DROP ", "TRUNCATE ", "DELETE ", "SHUTDOWN", "STARTUP", "GRANT ", "REVOKE "}

TABLESPACE_EXTEND_TRIGGER_PCT = 90.0
TABLESPACE_EXTEND_MIN_INITIAL_GB = 1
TABLESPACE_EXTEND_MAX_INITIAL_GB = 64
TABLESPACE_EXTEND_MIN_NEXT_MB = 64
TABLESPACE_EXTEND_MAX_NEXT_MB = 2048
TABLESPACE_EXTEND_MIN_MAX_GB = 1
TABLESPACE_EXTEND_MAX_MAX_GB = 1024

BLOCKING_WAIT_WARNING_SECONDS = 60
BLOCKING_WAIT_KILL_THRESHOLD_SECONDS = 300
BLOCKED_SESSION_COUNT_KILL_THRESHOLD = 2
